Repository elit-altum/newman-dashboard, pull requests merged in 2021-08, with the labels that each got.

#41 refactor: add separate package.json for reporter
  .github/workflows/reporter.yml
  index.js
  package-lock.json
  package.json
  reporter/.eslintrc.json
  reporter/.nycrc.json
  reporter/package-lock.json
  reporter/package.json
  reporter/test/unit/index.test.js
  reporter/test/unit/lib/handlers/index.test.js
  reporter/test/unit/lib/utils/index.test.js
Labels: refactor

#43 Add scripts to install and test all sub-packages with single command
  .eslintignore
  .github/workflows/ci.yml
  .github/workflows/client.yml
  .github/workflows/daemon.yml
  .github/workflows/node.js.yml
  dashboard/package.json
  frontend/package.json
  npm/build.js
  npm/coverage.js
  npm/post-install.js
  npm/test-integration.js
  npm/test-lint.js
  npm/test-unit.js
  package-lock.json
  package.json
  reporter/package.json
Labels: enhancement, refactor

#44 fix: UI edge cases of handling test errors
  frontend/actions/index.js
  frontend/components/EmptyRuns.js
  frontend/components/RunData.js
  frontend/components/RunEvent.js
  frontend/pages/run/[id].js
  frontend/state/models/run.js
Labels: enhancement
